### ISSUE TITLE
Should mannish be all-synchronous all the time?

### ISSUE THREAD

**Issue by TehShrike** [TehShrike/mannish#4]
When I made mannish I thought it made sense for it to be focused around explicitly asynchronous requests.  Most interactions with stateful things are asynchronous anyway.

But eventually I did run into enough cases where I wanted to make synchronous (state-based) business logic accessible via a mediator, so I added the `Sync` methods.

They get the job done, but they make me feel dirty.  Now, not only do you have to know what the function name is and what it returns, you have to know if it's in the synchronous bucket or the asynchronous bucket.

Maybe this should all go away, and there should only be *synchronous* `call` and `provide` methods.

If you want asynchronous behavior, you can provide an `async` function or explicitly return a promise.

Consumers still have to know the return type of the service they're calling, but there's no weird two-bucket system for providers/callers.

This would change: https://github.com/TehShrike/mannish/blob/a16a3f17280ec8b6f6b5c09970a685cc11429c93/index.js#L7-L13

It currently does a few things that would be lost:
- if the function is not `async` and returns a value, it coerces the value to a Promise before returning it
- if the function is not `async` and throws an error, the error is caught and coerced to a rejected Promise

This line would also have to change to throw an error instead of returning a rejected Promise: https://github.com/TehShrike/mannish/blob/a16a3f17280ec8b6f6b5c09970a685cc11429c93/index.js#L15

In the wild world of yester-year this would seem dangerous to me.  But I use `async`/`await` everywhere now – in an `async` function, if I call a service on the mediator, a synchronously thrown error is effectively the same as a rejected promise to me.

And maybe it wouldn't even have been a problem in yester-year – maybe I was just being overly cautious.

**Comment by saibotsivad** [comment]
I have the same low-key annoyance with needing to know which bucket (sync/async) to put things in and call them from, and I think this would be a pretty good solution. 👍
